### ISSUE TITLE
Create user registration page

### ISSUE THREAD

**Issue by danmaninc** [danmaninc/stress-tester-front#1]
### Task
- [x] Create a form component where user can create a new account
- [ ] ~~Validate input fields~~ moved to #13 
- [x] Forward user to auth if he already has an account
### Resources
You can use `LoginForm` component as basement for new `RegisterForm` component.
