### ISSUE TITLE
Add syntax highlighting in CodeBlock component

### ISSUE THREAD

**Issue by danmaninc** [danmaninc/stress-tester-front#10]
### Task
- [x] Wait until `CodeBlock` component is created is completed.
- [x] Research way to add syntax highlighting
- [x] Implement such a way
